### ISSUE TITLE
No available on CPAN

### ISSUE THREAD

**Issue by marghidanu** [Grinnz/Minion-Backend-Redis#1]
Hey there, I was just looking to install the package via CPAN but it seems it wasn't published yet.

**Comment by Grinnz** [comment]
Hi,
I don't consider this to be CPAN quality at this time because it has significant performance issues. But if you still want to use it, it's installable from git:

`cpanm https://github.com/Grinnz/Minion-Backend-Redis.git`

**Comment by Grinnz** [comment]
Also note there has been an attempt to make a more efficient version but it was not posted yet, see the discussion here: https://groups.google.com/d/topic/mojolicious/YxCcwq6gGII/discussion

**Comment by marghidanu** [comment]
Thanks, I will give it a go directly from Github.

**Comment by fayland** [comment]
actually performance is not so important on a job solution since it will be run in backend.

we use cpanfile and carton to install the modules. so we still like it to be in CPAN with CAUTION in description maybe?

anyway, thanks for the info.
